[package]
name = "vm"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {workspace = true}
serde_json = {workspace = true}
anyhow = {workspace = true}
tokio-tungstenite = {workspace = true}
tokio = {workspace = true}
